feat: added regexp to customize scss selectors names
abak-press/legacy-config pull request #17
Opened 2020-04-02 11:48 UTC by Nats92

and removed duplicate declaration of PropertyCount
https://jira.railsc.ru/browse/ORDERS-2876

2020-04-02 11:48 UTC, Nats92 commented
@idbolshakov

2020-04-02 12:06 UTC, idbolshakov requested changes

2020-04-02 12:06 UTC, idbolshakov commented on scss.yml
> -  PropertyCount:
а это почему удалила?

2020-04-02 12:06 UTC, Nats92 commented on scss.yml
> -  PropertyCount:
а он дублируется. Там в коде есть

2020-04-02 12:07 UTC, Nats92 commented on scss.yml
> -  PropertyCount:
причем оба правила говорят что они отключены, я оставила просто отключеное без лишних строк

2020-04-02 12:20 UTC, Nats92 commented on scss.yml
> -  PropertyCount:
![image](https://user-images.githubusercontent.com/30652104/78248536-3c4aa580-7506-11ea-8eb8-da81ff6f6d66.png)

2020-04-02 12:26 UTC, idbolshakov approved these changes

2020-04-02 12:27 UTC, idbolshakov commented
@c1n1c

2020-04-03 08:42 UTC, c1n1c approved these changes

2020-04-03 08:42 UTC, merged